version: "3.8"
services:
  bot:
    build: .
    environment: 
      TZ: "Europe/Rome"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    volumes:
      - "./redisdata:/data"
    entrypoint: "redis-server --appendonly yes"
